---
name: "jellyfin-plugin-pushover"
guid: "F240D6BE-5743-441B-87F1-A70ECAC42642"
version: "3" # Please increment with each pull request
jellyfin_version: "10.5.0" # The earliest binary-compatible version
owner: "crobibero"
nicename: "Pushover"
description: "Send notifications via Pushover"
overview: "Send messages to a wide range of devices through Pushover."
category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Pushover.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
